import { createServerSupabase } from '@/lib/supabase-server'
import { NextRequest, NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

export async function GET(req: NextRequest) {
  const supabase = createServerSupabase()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const auditId = searchParams.get('id')
  if (!auditId) return NextResponse.json({ error: 'id required' }, { status: 400 })

  const { data: audit } = await supabase
    .from('audit_reports')
    .select('*')
    .eq('id', auditId)
    .eq('user_id', user.id)
    .single()

  if (!audit) return NextResponse.json({ error: 'Audit not found' }, { status: 404 })

  const checks = audit.checks || []
  const passing = checks.filter((c: any) => c.status === 'pass')
  const warnings = checks.filter((c: any) => c.status === 'warn')
  const failing = checks.filter((c: any) => c.status === 'fail')

  const categoriesHtml = audit.categories ? Object.entries(audit.categories).map(([cat, score]) =>
    `<tr><td style="padding:8px 12px;border-bottom:1px solid #eee;">${cat}</td><td style="padding:8px 12px;border-bottom:1px solid #eee;text-align:center;font-weight:700;color:${(score as number) >= 80 ? '#00d084' : (score as number) >= 50 ? '#ffa500' : '#ff4444'}">${score}/100</td></tr>`
  ).join('') : ''

  const checksHtml = (items: any[], color: string, label: string) => items.length === 0 ? '' : `
    <h3 style="color:${color};margin:24px 0 12px;">${label} (${items.length})</h3>
    ${items.map(c => `<div style="padding:10px 14px;margin:6px 0;background:${color}10;border-radius:8px;border-left:3px solid ${color}">
      <div style="font-weight:600;font-size:14px;">${c.title}</div>
      <div style="font-size:13px;color:#666;margin-top:2px;">${c.detail}</div>
    </div>`).join('')}`

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>SEO Audit Report — ${audit.url}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #333; max-width: 800px; margin: 0 auto; padding: 40px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div style="background:#2367a0;padding:24px 32px;border-radius:12px;margin-bottom:32px;color:#fff;">
    <h1 style="margin:0;font-size:24px;">AI SEO <span style="color:#68ccd1;">Audit Report</span></h1>
    <p style="margin:8px 0 0;opacity:0.8;font-size:14px;">Generated by AI SEO powered by CGMIMM</p>
  </div>

  <div style="display:flex;gap:16px;margin-bottom:24px;">
    <div style="flex:1;background:#f8f9fb;border-radius:10px;padding:20px;text-align:center;">
      <div style="font-size:42px;font-weight:800;color:${audit.overall_score >= 80 ? '#00d084' : audit.overall_score >= 50 ? '#ffa500' : '#ff4444'}">${audit.overall_score}</div>
      <div style="font-size:12px;color:#999;">Overall Score</div>
    </div>
    <div style="flex:1;background:#f8f9fb;border-radius:10px;padding:20px;text-align:center;">
      <div style="font-size:42px;font-weight:800;color:#2367a0;">${audit.grade || 'N/A'}</div>
      <div style="font-size:12px;color:#999;">Grade</div>
    </div>
    <div style="flex:1;background:#f8f9fb;border-radius:10px;padding:20px;text-align:center;">
      <div style="font-size:42px;font-weight:800;color:#ff4444;">${failing.length}</div>
      <div style="font-size:12px;color:#999;">Issues</div>
    </div>
    <div style="flex:1;background:#f8f9fb;border-radius:10px;padding:20px;text-align:center;">
      <div style="font-size:42px;font-weight:800;color:#00d084;">${passing.length}</div>
      <div style="font-size:12px;color:#999;">Passing</div>
    </div>
  </div>

  <p><strong>URL:</strong> ${audit.url}</p>
  <p><strong>Date:</strong> ${new Date(audit.created_at).toLocaleString()}</p>
  ${audit.summary ? `<p style="line-height:1.7;">${audit.summary}</p>` : ''}

  ${categoriesHtml ? `
  <h2 style="color:#2367a0;margin-top:32px;">Category Scores</h2>
  <table style="width:100%;border-collapse:collapse;">
    <thead><tr style="background:#f8f9fb;"><th style="padding:10px 12px;text-align:left;font-size:13px;color:#999;">Category</th><th style="padding:10px 12px;text-align:center;font-size:13px;color:#999;">Score</th></tr></thead>
    <tbody>${categoriesHtml}</tbody>
  </table>` : ''}

  ${checksHtml(failing, '#ff4444', 'Issues to Fix')}
  ${checksHtml(warnings, '#ffa500', 'Warnings')}
  ${checksHtml(passing, '#00d084', 'Passing')}

  <div style="margin-top:40px;padding:20px;background:#f8f9fb;border-radius:10px;text-align:center;font-size:13px;color:#999;">
    Report generated by <strong style="color:#2367a0;">AI SEO powered by CGMIMM</strong> — seo.cgmimm.com
  </div>
</body>
</html>`

  return new NextResponse(html, {
    headers: {
      'Content-Type': 'text/html',
      'Content-Disposition': `inline; filename="seo-audit-${audit.url.replace(/[^a-z0-9]/gi, '-')}.html"`,
    },
  })
}
