'use client'

import { useState } from 'react'

type Step = 1 | 2 | 3 | 4 | 5

const BUSINESS_CATEGORIES = [
  'Plumber', 'Electrician', 'HVAC Contractor', 'Roofer', 'Landscaper',
  'General Contractor', 'Painter', 'Flooring Contractor', 'Pest Control',
  'Cleaning Service', 'Auto Repair Shop', 'Restaurant', 'Dentist',
  'Chiropractor', 'Law Firm', 'Accountant', 'Real Estate Agent',
  'Insurance Agent', 'Hair Salon', 'Barbershop', 'Gym', 'Yoga Studio',
  'Veterinarian', 'Pet Store', 'Retail Store', 'Coffee Shop', 'Bakery',
  'Marketing Agency', 'IT Services', 'Web Designer', 'Photographer',
  'Event Venue', 'Hotel', 'Medical Clinic', 'Physical Therapist',
  'Mortgage Broker', 'Financial Advisor', 'Moving Company', 'Storage Facility',
]

const DAYS = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

const defaultHours = DAYS.reduce((acc, day) => ({
  ...acc,
  [day]: { open: true, from: '09:00', to: '17:00' }
}), {} as Record<string, { open: boolean; from: string; to: string }>)

export default function GBPCreatorPage() {
  const [step, setStep] = useState<Step>(1)
  const [generating, setGenerating] = useState(false)
  const [exported, setExported] = useState(false)

  // Step 1 — Business basics
  const [bizName, setBizName] = useState('')
  const [bizCategory, setBizCategory] = useState('')
  const [bizPhone, setBizPhone] = useState('')
  const [bizWebsite, setBizWebsite] = useState('')
  const [bizAddress, setBizAddress] = useState('')
  const [bizCity, setBizCity] = useState('')
  const [bizState, setBizState] = useState('')
  const [bizZip, setBizZip] = useState('')
  const [openingDate, setOpeningDate] = useState('')
  const [listingType, setListingType] = useState<'create' | 'claim'>('create')

  // Step 2 — Hours
  const [hours, setHours] = useState(defaultHours)

  // Step 3 — Service areas
  const [serviceAreas, setServiceAreas] = useState('')
  const [isServiceAreaBiz, setIsServiceAreaBiz] = useState(false)

  // Step 4 — Description
  const [description, setDescription] = useState('')
  const [aiGenerating, setAiGenerating] = useState(false)

  // Step 5 — Review
  const [checklist, setChecklist] = useState<Record<string, boolean>>({})

  function updateHour(day: string, field: string, value: any) {
    setHours(prev => ({ ...prev, [day]: { ...prev[day], [field]: value } }))
  }

  async function generateDescription() {
    const claudeKey = localStorage.getItem('riq_claude_key')
    if (!claudeKey) { alert('Add your Anthropic API key in Settings first'); return }
    setAiGenerating(true)
    try {
      const res = await fetch('https://api.anthropic.com/v1/messages', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-api-key': claudeKey, 'anthropic-version': '2023-06-01', 'anthropic-dangerous-direct-browser-access': 'true' },
        body: JSON.stringify({
          model: 'claude-sonnet-4-20250514',
          max_tokens: 400,
          system: 'You are a local SEO expert. Write an optimized Google Business Profile description. It must be under 750 characters, include the business name and city, highlight key services, and include a natural call to action. Do not use hashtags or emojis. Write in plain text only.',
          messages: [{ role: 'user', content: `Business name: ${bizName}\nCategory: ${bizCategory}\nCity: ${bizCity}, ${bizState}\nService areas: ${serviceAreas}\nWrite an optimized GBP description.` }],
        }),
      })
      const data = await res.json()
      const text = data.content?.filter((b: any) => b.type === 'text').map((b: any) => b.text).join('') || ''
      setDescription(text.trim())
    } catch (err) { alert('Could not generate description') }
    finally { setAiGenerating(false) }
  }

  function exportGuide() {
    const openHours = DAYS.filter(d => hours[d].open).map(d => `${d}: ${hours[d].from} - ${hours[d].to}`).join('\n')
    const content = `GOOGLE BUSINESS PROFILE SETUP GUIDE
=====================================
Generated by Marketing Machine SEO
=====================================

LISTING TYPE: ${listingType === 'create' ? 'Create New Listing' : 'Claim Existing Listing'}

STEP 1 - GO TO
https://business.google.com
Click "Manage now" or "Add your business"

STEP 2 - BUSINESS INFORMATION
Business Name: ${bizName}
Category: ${bizCategory}
Phone: ${bizPhone}
Website: ${bizWebsite}
Address: ${bizAddress}, ${bizCity}, ${bizState} ${bizZip}
Opening Date: ${openingDate}
Service Area Business: ${isServiceAreaBiz ? 'Yes' : 'No'}

STEP 3 - BUSINESS HOURS
${openHours}

STEP 4 - SERVICE AREAS
${serviceAreas}

STEP 5 - BUSINESS DESCRIPTION (copy exactly)
${description}

STEP 6 - AFTER VERIFICATION CHECKLIST
[ ] Add at least 10 photos (exterior, interior, team, products/services)
[ ] Add all services with descriptions and prices
[ ] Add products if applicable
[ ] Enable messaging
[ ] Set up booking link if applicable
[ ] Add Q&A with common questions and answers
[ ] Post your first Google Post
[ ] Ask first 5 customers for reviews
[ ] Add all service area zip codes
[ ] Verify your listing via postcard or phone

VERIFICATION TIPS
- Google will mail a postcard to your address with a PIN (5-7 days)
- Some businesses qualify for instant phone or video verification
- Do NOT edit your address after requesting verification - it resets the process
- Once verified, respond to the verification prompt within 30 days

OPTIMIZATION CHECKLIST AFTER GOING LIVE
[ ] Profile completeness score 100%
[ ] Primary category set correctly
[ ] Add 2-3 secondary categories
[ ] Business description filled (750 chars max)
[ ] All hours set including holidays
[ ] Website URL added
[ ] Phone number verified
[ ] Photos uploaded (minimum 10)
[ ] Services/products listed
[ ] First Google Post published
`
    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${bizName.replace(/\s+/g, '-')}-GBP-Setup-Guide.txt`
    a.click()
    setExported(true)
  }

  const card = { background: '#fff', border: '1px solid rgba(0,0,0,0.08)', borderRadius: '12px', padding: '1.5rem', marginBottom: '12px' }
  const inputStyle = { width: '100%', background: '#f8f9fb', border: '1px solid rgba(0,0,0,0.1)', borderRadius: '8px', padding: '0.55rem 0.85rem', fontSize: '13px', color: '#0d1b2e', outline: 'none', fontFamily: 'Open Sans, sans-serif' }
  const labelStyle = { fontSize: '11px', color: '#7a8fa8', marginBottom: '4px', display: 'block', textTransform: 'uppercase' as const, letterSpacing: '0.06em', fontFamily: 'Roboto Mono, monospace' }

  const steps = [
    { num: 1, label: 'Business Info' },
    { num: 2, label: 'Hours' },
    { num: 3, label: 'Service Areas' },
    { num: 4, label: 'Description' },
    { num: 5, label: 'Export Guide' },
  ]

  return (
    <div>
      <div style={{ marginBottom: '1.5rem' }}>
        <h2 style={{ fontSize: '20px', marginBottom: '4px' }}>GBP Location Creator</h2>
        <p style={{ fontSize: '13px', color: '#7a8fa8' }}>Create or claim a Google Business Profile — step by step guide with AI-optimized description</p>
      </div>

      {/* Progress steps */}
      <div style={{ display: 'flex', alignItems: 'center', marginBottom: '1.5rem', background: '#fff', border: '1px solid rgba(0,0,0,0.08)', borderRadius: '12px', padding: '1rem 1.5rem' }}>
        {steps.map((s, i) => (
          <div key={s.num} style={{ display: 'flex', alignItems: 'center', flex: i < steps.length - 1 ? 1 : 0 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }} onClick={() => setStep(s.num as Step)}>
              <div style={{ width: '28px', height: '28px', borderRadius: '50%', background: step === s.num ? '#1e90ff' : step > s.num ? '#00d084' : '#f0f4f8', color: step >= s.num ? '#fff' : '#7a8fa8', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '12px', fontWeight: 700, fontFamily: 'Roboto Mono, monospace', flexShrink: 0 }}>
                {step > s.num ? 'OK' : s.num}
              </div>
              <span style={{ fontSize: '12px', fontWeight: step === s.num ? 600 : 400, color: step === s.num ? '#1e90ff' : step > s.num ? '#00d084' : '#7a8fa8', whiteSpace: 'nowrap' }}>{s.label}</span>
            </div>
            {i < steps.length - 1 && <div style={{ flex: 1, height: '1px', background: step > s.num ? '#00d084' : '#e4eaf0', margin: '0 12px' }} />}
          </div>
        ))}
      </div>

      {/* STEP 1 */}
      {step === 1 && (
        <div style={card}>
          <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '16px', fontWeight: 700, marginBottom: '1.25rem' }}>Business Information</div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={labelStyle}>What do you want to do?</label>
            <div style={{ display: 'flex', gap: '8px' }}>
              {[{ value: 'create', label: 'Create new GBP listing' }, { value: 'claim', label: 'Claim existing listing' }].map(o => (
                <button key={o.value} onClick={() => setListingType(o.value as any)} style={{ flex: 1, padding: '10px', borderRadius: '8px', border: `1px solid ${listingType === o.value ? '#1e90ff' : 'rgba(0,0,0,0.1)'}`, background: listingType === o.value ? 'rgba(30,144,255,0.08)' : '#f8f9fb', color: listingType === o.value ? '#1e90ff' : '#4a6080', fontSize: '13px', fontWeight: listingType === o.value ? 600 : 400, cursor: 'pointer', fontFamily: 'Open Sans, sans-serif' }}>{o.label}</button>
              ))}
            </div>
            {listingType === 'claim' && (
              <div style={{ marginTop: '8px', padding: '10px 12px', background: 'rgba(255,165,0,0.08)', border: '1px solid rgba(255,165,0,0.2)', borderRadius: '8px', fontSize: '12px', color: '#7a8fa8' }}>
                To claim an existing listing: Go to business.google.com, search for your business, and click "Claim this business". You may need to verify ownership via postcard, phone, or email.
              </div>
            )}
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
            <div>
              <label style={labelStyle}>Business Name</label>
              <input type="text" style={inputStyle} placeholder="Acme Plumbing Co." value={bizName} onChange={e => setBizName(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>Primary Category</label>
              <select value={bizCategory} onChange={e => setBizCategory(e.target.value)} style={{ ...inputStyle }}>
                <option value="">Select category...</option>
                {BUSINESS_CATEGORIES.map(c => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <div>
              <label style={labelStyle}>Phone Number</label>
              <input type="text" style={inputStyle} placeholder="(210) 555-0100" value={bizPhone} onChange={e => setBizPhone(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>Website URL</label>
              <input type="text" style={inputStyle} placeholder="https://yoursite.com" value={bizWebsite} onChange={e => setBizWebsite(e.target.value)} />
            </div>
            <div style={{ gridColumn: '1 / -1' }}>
              <label style={labelStyle}>Street Address</label>
              <input type="text" style={inputStyle} placeholder="123 Main Street" value={bizAddress} onChange={e => setBizAddress(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>City</label>
              <input type="text" style={inputStyle} placeholder="San Antonio" value={bizCity} onChange={e => setBizCity(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>State</label>
              <input type="text" style={inputStyle} placeholder="TX" value={bizState} onChange={e => setBizState(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>ZIP Code</label>
              <input type="text" style={inputStyle} placeholder="78201" value={bizZip} onChange={e => setBizZip(e.target.value)} />
            </div>
            <div>
              <label style={labelStyle}>Opening Date</label>
              <input type="date" style={inputStyle} value={openingDate} onChange={e => setOpeningDate(e.target.value)} />
            </div>
          </div>

          <button className="btn btn-accent" onClick={() => setStep(2)} disabled={!bizName || !bizCategory || !bizCity}>Next: Business Hours</button>
        </div>
      )}

      {/* STEP 2 */}
      {step === 2 && (
        <div style={card}>
          <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '16px', fontWeight: 700, marginBottom: '1.25rem' }}>Business Hours</div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '1.25rem' }}>
            {DAYS.map(day => (
              <div key={day} style={{ display: 'grid', gridTemplateColumns: '120px 60px 100px 20px 100px', gap: '12px', alignItems: 'center', padding: '8px 12px', background: '#f8f9fb', borderRadius: '8px' }}>
                <span style={{ fontSize: '13px', fontWeight: 500, color: '#0d1b2e' }}>{day}</span>
                <label style={{ display: 'flex', alignItems: 'center', gap: '6px', cursor: 'pointer', fontSize: '12px', color: '#7a8fa8' }}>
                  <input type="checkbox" checked={hours[day].open} onChange={e => updateHour(day, 'open', e.target.checked)} />
                  Open
                </label>
                {hours[day].open ? (
                  <>
                    <input type="time" value={hours[day].from} onChange={e => updateHour(day, 'from', e.target.value)} style={{ ...inputStyle, padding: '4px 8px', fontSize: '12px' }} />
                    <span style={{ textAlign: 'center', color: '#7a8fa8', fontSize: '12px' }}>to</span>
                    <input type="time" value={hours[day].to} onChange={e => updateHour(day, 'to', e.target.value)} style={{ ...inputStyle, padding: '4px 8px', fontSize: '12px' }} />
                  </>
                ) : (
                  <span style={{ fontSize: '12px', color: '#ff4444', gridColumn: '3 / 6' }}>Closed</span>
                )}
              </div>
            ))}
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-ghost" onClick={() => setStep(1)}>Back</button>
            <button className="btn btn-accent" onClick={() => setStep(3)}>Next: Service Areas</button>
          </div>
        </div>
      )}

      {/* STEP 3 */}
      {step === 3 && (
        <div style={card}>
          <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '16px', fontWeight: 700, marginBottom: '1.25rem' }}>Service Areas</div>

          <div style={{ marginBottom: '1rem' }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', fontSize: '13px', color: '#4a6080', marginBottom: '12px' }}>
              <input type="checkbox" checked={isServiceAreaBiz} onChange={e => setIsServiceAreaBiz(e.target.checked)} />
              This is a Service Area Business (SAB) — I go to customers, they do not come to my location
            </label>
            {isServiceAreaBiz && (
              <div style={{ padding: '10px 12px', background: 'rgba(30,144,255,0.05)', border: '1px solid rgba(30,144,255,0.15)', borderRadius: '8px', fontSize: '12px', color: '#4a6080', marginBottom: '12px' }}>
                As a SAB, you can hide your physical address on Google Maps. Google will still use your address for verification but won't show it publicly.
              </div>
            )}
          </div>

          <div style={{ marginBottom: '1.25rem' }}>
            <label style={labelStyle}>Service Areas (cities, counties, or zip codes)</label>
            <textarea
              value={serviceAreas}
              onChange={e => setServiceAreas(e.target.value)}
              placeholder="San Antonio, TX&#10;Bexar County&#10;New Braunfels, TX&#10;78201, 78202, 78203"
              rows={6}
              style={{ ...inputStyle, resize: 'vertical' }}
            />
            <div style={{ fontSize: '11px', color: '#7a8fa8', marginTop: '4px' }}>Enter one per line. Google allows up to 20 service areas.</div>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-ghost" onClick={() => setStep(2)}>Back</button>
            <button className="btn btn-accent" onClick={() => setStep(4)}>Next: Description</button>
          </div>
        </div>
      )}

      {/* STEP 4 */}
      {step === 4 && (
        <div style={card}>
          <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '16px', fontWeight: 700, marginBottom: '1.25rem' }}>Business Description</div>

          <div style={{ marginBottom: '1rem', padding: '10px 14px', background: 'rgba(30,144,255,0.05)', border: '1px solid rgba(30,144,255,0.15)', borderRadius: '8px', fontSize: '12px', color: '#4a6080', lineHeight: 1.6 }}>
            Google allows up to 750 characters. Include your main services, city, and a call to action. Do not include URLs, hours, or promotional language like "best" or "#1".
          </div>

          <div style={{ marginBottom: '1rem' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '4px' }}>
              <label style={labelStyle}>Description</label>
              <span style={{ fontSize: '11px', color: description.length > 700 ? '#ff4444' : '#7a8fa8', fontFamily: 'Roboto Mono, monospace' }}>{description.length}/750</span>
            </div>
            <textarea
              value={description}
              onChange={e => setDescription(e.target.value)}
              placeholder="Write your business description here or use AI to generate one..."
              rows={6}
              maxLength={750}
              style={{ ...inputStyle, resize: 'vertical' }}
            />
          </div>

          <div style={{ display: 'flex', gap: '8px', marginBottom: '1.25rem' }}>
            <button className="btn btn-ghost" onClick={generateDescription} disabled={aiGenerating || !bizName || !bizCategory} style={{ fontSize: '13px' }}>
              {aiGenerating ? 'Generating...' : 'Generate with AI'}
            </button>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button className="btn btn-ghost" onClick={() => setStep(3)}>Back</button>
            <button className="btn btn-accent" onClick={() => setStep(5)}>Next: Export Guide</button>
          </div>
        </div>
      )}

      {/* STEP 5 */}
      {step === 5 && (
        <div style={card}>
          <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '16px', fontWeight: 700, marginBottom: '1.25rem' }}>Review and Export</div>

          {/* Summary */}
          <div style={{ background: '#f8f9fb', borderRadius: '10px', padding: '1.25rem', marginBottom: '1.25rem' }}>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px', marginBottom: '12px' }}>
              {[
                { label: 'Business', value: bizName },
                { label: 'Category', value: bizCategory },
                { label: 'Phone', value: bizPhone },
                { label: 'Website', value: bizWebsite },
                { label: 'Address', value: `${bizAddress}, ${bizCity}, ${bizState} ${bizZip}` },
                { label: 'Opening Date', value: openingDate || 'Not set' },
              ].map(s => (
                <div key={s.label}>
                  <div style={{ fontSize: '10px', color: '#7a8fa8', textTransform: 'uppercase', letterSpacing: '0.06em', fontFamily: 'Roboto Mono, monospace', marginBottom: '2px' }}>{s.label}</div>
                  <div style={{ fontSize: '13px', color: '#0d1b2e', fontWeight: 500 }}>{s.value || 'Not set'}</div>
                </div>
              ))}
            </div>
            <div style={{ borderTop: '1px solid rgba(0,0,0,0.06)', paddingTop: '12px' }}>
              <div style={{ fontSize: '10px', color: '#7a8fa8', textTransform: 'uppercase', letterSpacing: '0.06em', fontFamily: 'Roboto Mono, monospace', marginBottom: '4px' }}>Description</div>
              <div style={{ fontSize: '12px', color: '#4a6080', lineHeight: 1.6 }}>{description || 'No description added'}</div>
            </div>
          </div>

          {/* What happens next */}
          <div style={{ marginBottom: '1.25rem' }}>
            <div style={{ fontFamily: 'Montserrat, sans-serif', fontSize: '14px', fontWeight: 600, marginBottom: '0.75rem' }}>What happens after you submit to Google</div>
            {[
              { step: '1', text: 'Google reviews your listing — usually approved within 1-3 business days' },
              { step: '2', text: 'You receive a verification postcard at your address (5-7 days) or may qualify for instant verification' },
              { step: '3', text: 'Enter the PIN from the postcard to verify and go live' },
              { step: '4', text: 'Add photos, posts, and respond to reviews to boost your ranking' },
            ].map(s => (
              <div key={s.step} style={{ display: 'flex', gap: '10px', padding: '8px 0', borderBottom: '1px solid rgba(0,0,0,0.05)' }}>
                <div style={{ width: '22px', height: '22px', borderRadius: '50%', background: 'rgba(30,144,255,0.1)', color: '#1e90ff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '11px', fontWeight: 700, flexShrink: 0, fontFamily: 'Roboto Mono, monospace' }}>{s.step}</div>
                <div style={{ fontSize: '13px', color: '#4a6080', lineHeight: 1.5 }}>{s.text}</div>
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <button className="btn btn-ghost" onClick={() => setStep(4)}>Back</button>
            <button className="btn btn-accent" onClick={exportGuide} style={{ fontSize: '13px' }}>
              {exported ? 'Downloaded!' : 'Download Setup Guide'}
            </button>
            <a href="https://business.google.com" target="_blank" className="btn btn-ghost" style={{ fontSize: '13px', textDecoration: 'none' }}>
              Open Google Business
            </a>
          </div>
        </div>
      )}
    </div>
  )
}
