// Common Google Business Profile categories. This is a curated shortlist of ~150 of the
// most-used categories for the datalist-backed business type input. Users can pick one or
// type their own — the exact text flows to the AI prompt.
export const BUSINESS_CATEGORIES: string[] = [
  // Home services
  'Roofing contractor',
  'Plumber',
  'Electrician',
  'HVAC contractor',
  'Painter',
  'Landscaper',
  'Lawn care service',
  'Tree service',
  'Pest control service',
  'House cleaning service',
  'Carpet cleaning service',
  'Window cleaning service',
  'Pressure washing service',
  'Handyman',
  'General contractor',
  'Remodeling contractor',
  'Flooring contractor',
  'Concrete contractor',
  'Fence contractor',
  'Deck builder',
  'Pool contractor',
  'Garage door service',
  'Gutter cleaning service',
  'Chimney sweep',
  'Home inspection service',
  'Solar panel installer',
  'Septic system service',
  'Water damage restoration',
  'Mold remediation',
  'Locksmith',
  'Moving company',
  'Junk removal service',
  'Storage facility',

  // Automotive
  'Auto repair shop',
  'Auto body shop',
  'Tire shop',
  'Oil change service',
  'Car dealer',
  'Used car dealer',
  'Car wash',
  'Auto detailing',
  'Transmission shop',
  'Motorcycle repair shop',
  'Towing service',

  // Medical / health
  'Dentist',
  'Orthodontist',
  'Pediatric dentist',
  'Oral surgeon',
  'Doctor',
  'Family practice physician',
  'Pediatrician',
  'Dermatologist',
  'Chiropractor',
  'Optometrist',
  'Physical therapist',
  'Urgent care center',
  'Medical spa',
  'Mental health service',
  'Psychologist',
  'Therapist',
  'Veterinarian',
  'Audiologist',
  'Acupuncturist',
  'Weight loss service',
  'Plastic surgeon',

  // Legal & financial
  'Personal injury attorney',
  'Family law attorney',
  'Divorce attorney',
  'Criminal defense attorney',
  'Estate planning attorney',
  'Business attorney',
  'Immigration attorney',
  'Bankruptcy attorney',
  'Real estate attorney',
  'Accountant',
  'Tax preparation service',
  'Bookkeeping service',
  'Financial planner',
  'Insurance agency',
  'Mortgage broker',

  // Real estate
  'Real estate agency',
  'Real estate agent',
  'Property management company',
  'Commercial real estate agency',
  'Real estate appraiser',
  'Home builder',

  // Food & beverage
  'Restaurant',
  'Italian restaurant',
  'Mexican restaurant',
  'Chinese restaurant',
  'Japanese restaurant',
  'Thai restaurant',
  'Indian restaurant',
  'Pizza restaurant',
  'Sushi restaurant',
  'Seafood restaurant',
  'Steakhouse',
  'Barbecue restaurant',
  'Fast food restaurant',
  'Cafe',
  'Coffee shop',
  'Bakery',
  'Bar',
  'Brewery',
  'Winery',
  'Food truck',
  'Catering service',
  'Ice cream shop',
  'Juice bar',
  'Deli',

  // Beauty & wellness
  'Hair salon',
  'Barber shop',
  'Nail salon',
  'Day spa',
  'Massage therapist',
  'Tattoo shop',
  'Eyebrow threading service',
  'Waxing hair removal service',
  'Gym',
  'Personal trainer',
  'Yoga studio',
  'Pilates studio',
  'Crossfit box',
  'Martial arts school',

  // Pet
  'Pet groomer',
  'Pet boarding service',
  'Dog trainer',
  'Doggy day care',
  'Veterinary hospital',

  // Retail & ecommerce
  'Clothing store',
  "Women's clothing store",
  "Men's clothing store",
  'Jewelry store',
  'Shoe store',
  'Furniture store',
  'Home goods store',
  'Appliance store',
  'Electronics store',
  'Hardware store',
  'Sporting goods store',
  'Bookstore',
  'Toy store',
  'Gift shop',
  'Florist',
  'Grocery store',
  'Liquor store',
  'Vape shop',
  'Cannabis dispensary',
  'Online store',

  // Professional services / B2B
  'Marketing agency',
  'SEO agency',
  'Digital marketing agency',
  'Advertising agency',
  'Web design company',
  'Software company',
  'SaaS company',
  'IT support company',
  'Business consultant',
  'Management consulting firm',
  'Public relations firm',
  'Graphic designer',
  'Photographer',
  'Videographer',
  'Video production company',
  'Event planner',
  'Wedding planner',
  'Commercial cleaning service',
  'Staffing agency',
  'Translation service',
  'Printing service',
  'Architect',
  'Engineer',
  'Surveyor',

  // Education & nonprofit
  'Tutoring service',
  'Music school',
  'Dance school',
  'Language school',
  'Private school',
  'Preschool',
  'Childcare center',
  'Driving school',
  'Online course',
  'Nonprofit organization',
  'Church',
  'Charity',

  // Travel & hospitality
  'Hotel',
  'Bed & breakfast',
  'Vacation rental',
  'Travel agency',
  'Tour operator',
  'Taxi service',
  'Limo service',
  'Airport shuttle',

  // Entertainment
  'Event venue',
  'Wedding venue',
  'Banquet hall',
  'Golf course',
  'Bowling alley',
  'Escape room',
  'Arcade',

  // Other common
  'Funeral home',
  'Dry cleaner',
  'Tailor',
  'Cobbler',
  'Car rental agency',
  'Self-storage facility',
  'Notary',
  'Passport photo service',
  'Mailbox rental service',
]
