import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { getUser } from '@/lib/auth'

export const dynamic = 'force-dynamic'

// GET /api/disavow?siteId=...&format=json|txt
export async function GET(req: NextRequest) {
  const user = await getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const siteId = searchParams.get('siteId')
  const format = searchParams.get('format') || 'json'
  if (!siteId) return NextResponse.json({ error: 'siteId required' }, { status: 400 })

  const rows = await prisma.disavowed_backlinks.findMany({
    where: { site_id: siteId, user_id: user.id },
    orderBy: { created_at: 'desc' },
  })

  if (format === 'txt') {
    const lines: string[] = [
      '# Google Disavow file — generated by SEO by CGMIMM',
      `# Generated: ${new Date().toISOString()}`,
      `# Total entries: ${rows.length}`,
      '',
    ]
    for (const r of rows) {
      if (r.reason) lines.push(`# ${r.reason}`)
      if (r.scope === 'domain') lines.push(`domain:${r.target}`)
      else lines.push(r.target)
    }
    return new NextResponse(lines.join('\n'), {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="disavow-${siteId}.txt"`,
      },
    })
  }

  return NextResponse.json({ entries: rows })
}

// POST /api/disavow — add entry. body: { siteId, scope, target, reason? }
export async function POST(req: NextRequest) {
  const user = await getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { siteId, scope, target, reason } = await req.json()
  if (!siteId || !scope || !target) return NextResponse.json({ error: 'siteId, scope, target required' }, { status: 400 })
  if (!['domain', 'url'].includes(scope)) return NextResponse.json({ error: 'scope must be domain or url' }, { status: 400 })

  // Scope: ensure the caller owns the site before writing.
  const site = await prisma.sites.findFirst({ where: { id: siteId, user_id: user.id }, select: { id: true } })
  if (!site) return NextResponse.json({ error: 'Forbidden' }, { status: 403 })

  try {
    // onConflict (site_id,scope,target) + ignoreDuplicates: insert, no-op on existing
    await prisma.disavowed_backlinks.upsert({
      where: { site_id_scope_target: { site_id: siteId, scope, target } },
      create: { site_id: siteId, user_id: user.id, scope, target, reason: reason || null },
      update: {},
    })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
  return NextResponse.json({ success: true })
}

// DELETE /api/disavow?id=...
export async function DELETE(req: NextRequest) {
  const user = await getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const id = searchParams.get('id')
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })

  try {
    await prisma.disavowed_backlinks.deleteMany({ where: { id, user_id: user.id } })
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
  return NextResponse.json({ success: true })
}
