import { NextRequest, NextResponse } from 'next/server'
import { createServerSupabase } from '@/lib/supabase-server'

export const dynamic = 'force-dynamic'

// GET /api/disavow?siteId=...&format=json|txt
export async function GET(req: NextRequest) {
  const supabase = createServerSupabase()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const siteId = searchParams.get('siteId')
  const format = searchParams.get('format') || 'json'
  if (!siteId) return NextResponse.json({ error: 'siteId required' }, { status: 400 })

  const { data } = await supabase.from('disavowed_backlinks')
    .select('*').eq('site_id', siteId).eq('user_id', user.id).order('created_at', { ascending: false })
  const rows = data || []

  if (format === 'txt') {
    const lines: string[] = [
      '# Google Disavow file — generated by SEO by CGMIMM',
      `# Generated: ${new Date().toISOString()}`,
      `# Total entries: ${rows.length}`,
      '',
    ]
    for (const r of rows) {
      if (r.reason) lines.push(`# ${r.reason}`)
      if (r.scope === 'domain') lines.push(`domain:${r.target}`)
      else lines.push(r.target)
    }
    return new NextResponse(lines.join('\n'), {
      headers: {
        'Content-Type': 'text/plain; charset=utf-8',
        'Content-Disposition': `attachment; filename="disavow-${siteId}.txt"`,
      },
    })
  }

  return NextResponse.json({ entries: rows })
}

// POST /api/disavow — add entry. body: { siteId, scope, target, reason? }
export async function POST(req: NextRequest) {
  const supabase = createServerSupabase()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { siteId, scope, target, reason } = await req.json()
  if (!siteId || !scope || !target) return NextResponse.json({ error: 'siteId, scope, target required' }, { status: 400 })
  if (!['domain', 'url'].includes(scope)) return NextResponse.json({ error: 'scope must be domain or url' }, { status: 400 })

  const { error } = await supabase.from('disavowed_backlinks').upsert(
    { site_id: siteId, user_id: user.id, scope, target, reason: reason || null },
    { onConflict: 'site_id,scope,target', ignoreDuplicates: true }
  )
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ success: true })
}

// DELETE /api/disavow?id=...
export async function DELETE(req: NextRequest) {
  const supabase = createServerSupabase()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = new URL(req.url)
  const id = searchParams.get('id')
  if (!id) return NextResponse.json({ error: 'id required' }, { status: 400 })

  const { error } = await supabase.from('disavowed_backlinks').delete().eq('id', id).eq('user_id', user.id)
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json({ success: true })
}
